fix: allow cursor to move to the next line at the line end
wind-editor/wind pull request #2
Opened 2023-10-02 19:05 UTC by 0Ky

### Description

- Enhanced cursor movement logic to allow the cursor to move to the next line when the right arrow key is pressed at the end of a line, and vice versa (move to the previous line when the left arrow key is pressed at the start of a line).

- Prevented the cursor from moving beyond the start or end of the document.

- Used the `len()` method on the rows vector of the Document struct to determine the total number of rows in the document, ensuring accurate cursor movement and boundary checking.

2023-10-03 02:33 UTC, yhyadev requested changes
It's just overflows the document current column length

2023-10-03 02:46 UTC, 0Ky commented
> It's just overflows the document current column length

I have made changes, can you please review?

- Modify cursor's column position in set_cursor to account for scroll_offset.column.
- Ensure cursor is correctly positioned on the screen during horizontal scrolls.
- Properly adjust cursor column position when transitioning between lines, this closes #1
- Address potential visibility issues due to both horizontal and vertical scrolls.

2023-10-03 02:48 UTC, yhyadev requested changes
Could you store the position history? We need it to remember the past cursor position, But i don't see any history here

2023-10-03 03:00 UTC, 0Ky commented
> Could you store the position history? We need it to remember the past cursor position, But i don't see any history here

Do you want me to create another PR for that? Your request seems like an enhancement that could be used for other features that are yet to be implemented. The current PR is focused on fixing the current "cursor movement logic inconsistencies".

2023-10-03 03:03 UTC, yhyadev commented
> > Could you store the position history? We need it to remember the past cursor position, But i don't see any history here
> 
> Do you want me to create another PR for that? Your request seems like an enhancement that could be used for other features that are yet to be implemented. The current PR is focused on fixing the current "cursor movement logic inconsistencies".

It was a feature before you made this PR so it's not a new thing to make a new PR for it @0Ky

2023-10-03 03:16 UTC, yhyadev requested changes
This doesn't change anything, Just a new variable

2023-10-03 03:19 UTC, yhyadev requested changes
Also that's just a variable

2023-10-03 03:22 UTC, 0Ky commented
> This doesn't change anything, Just a new variable

I was under the impression that you were referring to that variable, can you show the exact commit or line that you're talking about? What exactly was the "feature" you had before I made the PR which you believe removed it?

2023-10-03 03:31 UTC, yhyadev commented
> > This doesn't change anything, Just a new variable
> 
> I was under the impression that you were referring to that variable, can you show the exact commit or line that you're talking about? What exactly was the "feature" you had before I made the PR which you believe removed it?

While you are going to right
```rs
self.editor.position.column = self.editor.position.column.saturating_add(1);
                    self.editor.position.history.column =
                        self.editor.position.history.column.saturating_add(1);
```

When you go down
```rs
                    self.editor.position.row = self.editor.position.row.saturating_add(1);
                    self.editor.position.column =
                        std::cmp::min(self.editor.position.history.column.saturating_sub(self.editor.scroll_offset.column), next_row_length.saturating_sub(self.editor.scroll_offset.column));
                }
```

It will choose between the minimum value between the current document length and the position history

2023-10-03 04:06 UTC, 0Ky commented
> It will choose the minimum value between the current document length and the position history of the previous column

Oh, when you move up or down between lines of different lengths, you want to remember the horizontal position they were last on (even if the new line is shorter), so that if they return to a longer line, the cursor will attempt to go back to its remembered horizontal position.

2023-10-03 10:04 UTC, yhyadev requested changes
Ok, We done with the fancy thing, Let's begin to really scroll up and down, Because we are now able to scroll left and right only

2023-10-04 23:01 UTC, 0Ky commented
@yhyadev Oke, Here are the changes that were made:

- Added support for scrolling up and down for all the keys.
- Made further refinement of the cursor movement logic.
- Fixed a conditional logic error that prevented drawing the first line of the document.
- Removed unused variables.

2023-10-05 03:55 UTC, yhyadev approved these changes
LGTM 👍

2023-10-05 03:56 UTC, merged